spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web-security
    username: web
    password: 1
  jpa:
    properties:
      hibernate:
        show_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
